# Generated by Django 5.0.6 on 2024-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images')),
                ('designation', models.CharField(max_length=50)),
                ('emailAddress', models.EmailField(max_length=50, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
